/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prolab3;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author bayram
 */
public class Giris extends javax.swing.JFrame {
static String Email,Sifre,Dogrusifre,Dogumtarihi,Kullanıcıadı;

    public String getKalınanprogram1() {
        return kalınanprogram1;
    }

    public void setKalınanprogram1(String kalınanprogram1) {
        this.kalınanprogram1 = kalınanprogram1;
    }

    public String getKalınansüre1() {
        return kalınansüre1;
    }

    public void setKalınansüre1(String kalınansüre1) {
        this.kalınansüre1 = kalınansüre1;
    }

    public int getKalınanbölüm1() {
        return kalınanbölüm1;
    }

    public void setKalınanbölüm1(int kalınanbölüm1) {
        this.kalınanbölüm1 = kalınanbölüm1;
    }
            String kalınanprogram1;
            String kalınansüre1;
            int kalınanbölüm1;
//KullanıcıBilgileri a=new KullanıcıBilgileri();
    public String getEmail() {
        return Email;
    }

    public void setEmail(String Email) {
        this.Email = Email;
    }
    /**
     * Creates new form NewJFrame
     */
    public Giris() {
        initComponents();     
       this.getContentPane().setBackground(Color.darkGray);
            jLabel1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textField1 = new java.awt.TextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(Color.red);

        textField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField1ActionPerformed(evt);
            }
        });

        jButton1.setText("Giris yap");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Kayıt Ol");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("E-mail veya Sifre Yanlış");

        jPasswordField1.setToolTipText("Sifre");

        jLabel2.setText("E-mail");

        jLabel3.setText("Şifre");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(529, 529, 529)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(377, 377, 377)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(textField1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(94, 94, 94)
                                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(129, 129, 129)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(600, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(253, 253, 253)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jButton1)
                .addGap(29, 29, 29)
                .addComponent(jButton2)
                .addContainerGap(555, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   
    Email=textField1.getText();
    Sifre=jPasswordField1.getText();
    setEmail(Email);
    Baglanti.yap();
    Dogrusifre=Baglanti.emailara(Email);
    Dogumtarihi=Baglanti.dogumtarihigönder(Email);
    Kullanıcıadı=Baglanti.kullanıcıadıgönder(Email);
    if(Sifre.compareTo(Dogrusifre)!=0){
        jLabel1.setVisible(true);
    }
        
    else{       
        KullanıcıBilgileri.setEmail(Email);
        KullanıcıBilgileri.setDogumtarihi(Dogumtarihi);
        KullanıcıBilgileri.setKullanıcıAdı(Kullanıcıadı);
        String sql="SELECT * FROM kullanıcıprogram";/*where kullanıcıprogramemail='"+Email+"'";*/
        String sırala="SELECT * FROM kullanıcıprogram ORDER BY sayac DESC";
        
        Baglanti.ismegöresorgula(sırala);
        ResultSet sorgu=Baglanti.ismegöresorgula(sql);
        String kalanemail="-1";
        String kalınanprogram="-1";
        String kalınansüre="-1";
        String mail="-1";
        int kalınanbölüm=-1;
         
        try {
            while(sorgu.next()){
                mail=sorgu.getString("kullaniciprogramemail");
                kalınansüre=sorgu.getString("izlemesüresi");
                if(Email.compareTo(mail)==0){                    
                kalanemail=sorgu.getString("kullaniciprogramemail");              
                kalınanprogram=sorgu.getString("kaldigiprogram");
                kalınansüre=sorgu.getString("izlemesüresi");
                kalınanbölüm=sorgu.getInt("kaldigibolum");
                setKalınanprogram1(kalınanprogram);
                setKalınansüre1(kalınansüre);
                setKalınanbölüm1(kalınanbölüm);
               }
            }
        } catch (SQLException ex) {
            Logger.getLogger(Giris.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if(Email.compareTo(kalanemail)==0){
            JFrame frame=new JFrame();
            JLabel label=new JLabel();
            JLabel label2=new JLabel();
            JButton buton1=new JButton("Evet");
            JButton buton2=new JButton("Anasayfa");
            label.setText("En son "+kalınanprogram+" "+kalınanbölüm+".bölüm "+kalınansüre+" 'de kaldınız.");  
            label2.setText("Kaldığınız yerden devam etmek ister misiniz?");
            frame.setBounds(150,150,400,200);
            frame.setVisible(true);
            frame.setLayout(null);
            frame.add(label);
            frame.add(label2);
            frame.add(buton1);
            frame.add(buton2);
            buton1.setBounds(10, 100, 100,40);
            buton2.setBounds(150, 100, 100,40);
            label.setBounds(10,25, 400, 20);
            label2.setBounds(10,50, 300, 20);
            buton2.addActionListener(new ActionListener(){
            
            public void actionPerformed(ActionEvent a){
            
              new KullanıcıPaneli().setVisible(true);
              dispose();
             
             
            }
            
            
        });
            buton1.addActionListener(new ActionListener(){
            
            public void actionPerformed(ActionEvent a){
            KullanıcıPaneli panel=new KullanıcıPaneli();
            
              new KullanıcıPaneli(kalınanprogram1,kalınansüre1,kalınanbölüm1).setVisible(true);
              frame.dispose();
              dispose();
             
             
            }
            
            
        });
            buton2.addActionListener(new ActionListener(){
            
            public void actionPerformed(ActionEvent a){
            KullanıcıPaneli panel=new KullanıcıPaneli();
            
        //      new KullanıcıPaneli().setVisible(true);
              frame.dispose();
              dispose();
             
             
            }
            
            
        });
        }
        else{
            new KullanıcıPaneli().setVisible(true);
        
            dispose();
        }
        
    
    }
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new Kayıt().setVisible(true);
        Baglanti.yap();
        
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Giris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Giris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Giris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Giris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Giris().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jPasswordField1;
    private java.awt.TextField textField1;
    // End of variables declaration//GEN-END:variables
}
