/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prolab3;

import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static prolab3.Baglanti.myConn;

/**
 *
 * @author bayram
 */
public class Kayıt extends javax.swing.JFrame {

    /**
     * Creates new form Kayıt
     */
    public Kayıt() {
        initComponents();
        jLabel1.setVisible(false);
       
         this.getContentPane().setBackground(Color.darkGray);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textField1 = new java.awt.TextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        textField3 = new java.awt.TextField();
        jComboBox4 = new javax.swing.JComboBox<>();
        jComboBox5 = new javax.swing.JComboBox<>();
        jComboBox6 = new javax.swing.JComboBox<>();
        jComboBox7 = new javax.swing.JComboBox<>();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1280, 1024));
        setMinimumSize(new java.awt.Dimension(1280, 1024));
        setResizable(false);
        getContentPane().setLayout(null);
        getContentPane().add(textField1);
        textField1.setBounds(566, 168, 120, 20);
        textField1.getAccessibleContext().setAccessibleName("");

        jButton1.setText("Kayıt ol");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(580, 350, 67, 23);

        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("Kayıt Basarısız.Girilen E-mail adresi kullanımda.");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(510, 400, 280, 26);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aksiyon ve Macera", "Belgesel", "Bilim Kurgu ve Fantastik Yapımlar", "Bilim ve Doğa", "Çocuk ve Aile", "Drama", "Gerilim", "Komedi", "Korku", "Romantik", "Reality Program" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(358, 312, 170, 30);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aksiyon ve Macera", "Belgesel", "Bilim Kurgu ve Fantastik Yapımlar", "Bilim ve Doğa", "Çocuk ve Aile", "Drama", "Gerilim", "Komedi", "Korku", "Romantik", "Reality Program" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(538, 312, 170, 30);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aksiyon ve Macera", "Belgesel", "Bilim Kurgu ve Fantastik Yapımlar", "Bilim ve Doğa", "Çocuk ve Aile", "Drama", "Gerilim", "Komedi", "Korku", "Romantik", "Reality Program" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox3);
        jComboBox3.setBounds(714, 312, 170, 30);

        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("Aşağıdan 3 Farklı Program Türü Seçiniz");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(532, 269, 273, 14);

        jLabel3.setText("Kullanıcı Adı");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(408, 54, 69, 14);

        jLabel4.setText("Doğum Tarihi(Gün/Ay/Yıl)");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(408, 110, 150, 14);

        jLabel5.setText("E-mail Adresi");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(408, 168, 150, 20);

        jLabel6.setText("Şifre");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(408, 225, 35, 14);
        getContentPane().add(textField3);
        textField3.setBounds(566, 48, 120, 20);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        getContentPane().add(jComboBox4);
        jComboBox4.setBounds(566, 110, 50, 22);

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        getContentPane().add(jComboBox5);
        jComboBox5.setBounds(630, 110, 50, 22);

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010" }));
        getContentPane().add(jComboBox6);
        jComboBox6.setBounds(690, 110, 70, 22);

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "@hotmail.com", "@gmail.com" }));
        getContentPane().add(jComboBox7);
        jComboBox7.setBounds(696, 168, 130, 25);
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(566, 219, 120, 20);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));

        jLabel7.setText("Tür Seçiniz");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(75, 75, 75)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(95, 95, 95))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 460, 400, 340);

        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));

        jLabel8.setText("Tür Seçiniz");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(84, 84, 84)
                .addComponent(jLabel12)
                .addGap(96, 96, 96)
                .addComponent(jLabel13)
                .addContainerGap(129, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(440, 460, 400, 340);

        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));

        jLabel9.setText("Tür Seçiniz");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(77, 77, 77)
                .addComponent(jLabel14)
                .addGap(96, 96, 96)
                .addComponent(jLabel15)
                .addContainerGap(136, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(860, 460, 400, 340);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String Kullanıcı,Email,Dogumtarihi,sqlsorgu;
        String Sifre;
        Email=textField1.getText()+jComboBox7.getSelectedItem();
        Sifre=jPasswordField1.getText();
        Kullanıcı=textField3.getText();
       Dogumtarihi=""+jComboBox4.getSelectedItem()+"/"+jComboBox5.getSelectedItem()+"/"+jComboBox6.getSelectedItem();
      sqlsorgu= " INSERT INTO kullanıcılar (kullanıcıadı,kullanıcıemail,kullanıcısifre,kullanıcıdogumtarihi) VALUES ('"+Kullanıcı+"','"+Email+"','"+Sifre+"','"+Dogumtarihi+"')";
     //       sqlsorgu= " INSERT INTO kullanıcılar (kullanıcıadı,kullanıcıemail,kullanıcısifre,kullanıcıdogumtarihi) VALUES (?,?,?,?)";
    Baglanti.yap();
        
      
               boolean kayıt=Baglanti.kayıt(Email);
               System.out.println(kayıt);
        if(kayıt==true&&textField3.getSelectionEnd()>0&&textField1.getSelectionEnd()>0&&jPasswordField1.getSelectionEnd()>0&&(jComboBox1.getSelectedIndex()!=jComboBox2.getSelectedIndex()&&jComboBox1.getSelectedIndex()!=jComboBox3.getSelectedIndex()&&jComboBox2.getSelectedIndex()!=jComboBox3.getSelectedIndex())){   
            Baglanti.ekle(sqlsorgu);      
            jButton1.setVisible(false);
            JOptionPane.showMessageDialog(null, "Kayıt Basarili!Giriş Ekranına Yönlendiriliyosunuz.");
             new Giris().setVisible(true);
            dispose();
        }
        else{
            jLabel1.setText("Kayıt Basarısız.Girilen E-mail adresi kullanımda.");          
            if(jComboBox1.getSelectedIndex()==jComboBox2.getSelectedIndex()||jComboBox1.getSelectedIndex()==jComboBox3.getSelectedIndex()||jComboBox2.getSelectedIndex()==jComboBox3.getSelectedIndex()){
                jLabel1.setText("Lütfen Farklı Türler Seçiniz");
            }
            if(textField3.getSelectionEnd()<=0){
                jLabel1.setText("Kullanıcı Adı Boş Bırakılamaz.");
            }
           if( textField1.getSelectionEnd()<=0){
               jLabel1.setText("E-mail Boş Bırakılamaz.");
           }
           if( jPasswordField1.getSelectionEnd()<=0){
               jLabel1.setText("Şifre Boş Bırakılamaz.");
           }
               
          /*  if(jComboBox1.getSelectedIndex()==0||jComboBox2.getSelectedIndex()==0||jComboBox3.getSelectedIndex()==0){
                jLabel1.setText("Lütfen Tür Seçiniz");
            }       */     
            jLabel1.setVisible(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
               
        jLabel9.setText("En çok puan alan "+jComboBox3.getSelectedItem()+" filmleri/dizileri");
       String sırala="SELECT programadi,programtür.programtür_türıd,programlar_puan FROM programlar "
                + "INNER JOIN programtür ON programtür.programtür_programıd=programlar.program_ıd and programlar.programtürü=programtür.programtür_programıd "
                + "INNER JOIN tür ON programtür.programtür_türıd=tür.tür_ıd "
                + "WHERE tür.tür_programtürü like '%"+jComboBox2.getSelectedItem()+"%' ORDER BY programlar_puan DESC ";
       String sql="SELECT * From programlar";
       String sıfırla="SELECT * FROM netflixveritabani.programlar";
       Baglanti.yap();
      // Baglanti.ismegöresorgula(sırala);
       ResultSet myRs=null;
       String birinciadı="-1";
       String birincipuanı="-1";
       String ikinciadı="-1";
       String ikincipuanı="-1";
       myRs=Baglanti.ismegöresorgula(sırala);
       int i=0;
        try { 
            while(myRs.next()){
                if(i==0){
                    birinciadı=myRs.getString("programadi")+"    Puan:";
                    birincipuanı=myRs.getString("programlar_puan");
                    
                }
                if(i==1){
                    ikinciadı=myRs.getString("programadi")+"    Puan:";
                    ikincipuanı=myRs.getString("programlar_puan");
                    
                }
                
                i++;
            }
                } catch (SQLException ex) {
            Logger.getLogger(Kayıt.class.getName()).log(Level.SEVERE, null, ex);
        }
        jLabel14.setText(birinciadı+birincipuanı);
        jLabel15.setText(ikinciadı+ikincipuanı);
        Baglanti.ismegöresorgula(sıfırla);
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        
        jLabel7.setText("En çok puan alan "+jComboBox1.getSelectedItem()+" filmleri/dizileri");
        String sırala="SELECT programadi,programtür.programtür_türıd,programlar_puan FROM programlar "
                + "INNER JOIN programtür ON programtür.programtür_programıd=programlar.program_ıd and programlar.programtürü=programtür.programtür_programıd "
                + "INNER JOIN tür ON programtür.programtür_türıd=tür.tür_ıd "
                + "WHERE tür.tür_programtürü like '%"+jComboBox2.getSelectedItem()+"%' ORDER BY programlar_puan DESC ";
       String sql="SELECT * From programlar";
       String sıfırla="SELECT * FROM netflixveritabani.programlar";
       Baglanti.yap();
      // Baglanti.ismegöresorgula(sırala);
       ResultSet myRs=null;
       String birinciadı="-1";
       String birincipuanı="-1";
       String ikinciadı="-1";
       String ikincipuanı="-1";
       myRs=Baglanti.ismegöresorgula(sırala);
       int i=0;
        try { 
            while(myRs.next()){
                if(i==0){
                    birinciadı=myRs.getString("programadi")+"    Puan:";
                    birincipuanı=myRs.getString("programlar_puan");
                    
                }
                if(i==1){
                    ikinciadı=myRs.getString("programadi")+"    Puan:";
                    ikincipuanı=myRs.getString("programlar_puan");
                    
                }
                
                i++;
            }
                } catch (SQLException ex) {
            Logger.getLogger(Kayıt.class.getName()).log(Level.SEVERE, null, ex);
        }
        jLabel10.setText(birinciadı+birincipuanı);
        jLabel11.setText(ikinciadı+ikincipuanı);
        Baglanti.ismegöresorgula(sıfırla);
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
       jLabel8.setText("En çok puan alan "+jComboBox2.getSelectedItem()+" filmleri/dizileri");
       String sırala="SELECT programadi,programtür.programtür_türıd,programlar_puan FROM programlar "
                + "INNER JOIN programtür ON programtür.programtür_programıd=programlar.program_ıd and programlar.programtürü=programtür.programtür_programıd "
                + "INNER JOIN tür ON programtür.programtür_türıd=tür.tür_ıd "
                + "WHERE tür.tür_programtürü like '%"+jComboBox2.getSelectedItem()+"%' ORDER BY programlar_puan DESC ";
       String sql="SELECT * From programlar";
       String sıfırla="SELECT * FROM netflixveritabani.programlar";
       Baglanti.yap();
      // Baglanti.ismegöresorgula(sırala);
       ResultSet myRs=null;
       String birinciadı="-1";
       String birincipuanı="-1";
       String ikinciadı="-1";
       String ikincipuanı="-1";
       myRs=Baglanti.ismegöresorgula(sırala);
       int i=0;
        try { 
            while(myRs.next()){
                if(i==0){
                    birinciadı=myRs.getString("programadi")+"    Puan:";
                    birincipuanı=myRs.getString("programlar_puan");
                    
                }
                if(i==1){
                    ikinciadı=myRs.getString("programadi")+"    Puan:";
                    ikincipuanı=myRs.getString("programlar_puan");
                    
                }
                
                i++;
            }
                } catch (SQLException ex) {
            Logger.getLogger(Kayıt.class.getName()).log(Level.SEVERE, null, ex);
        }
        jLabel12.setText(birinciadı+birincipuanı);
        jLabel13.setText(ikinciadı+ikincipuanı);
        Baglanti.ismegöresorgula(sıfırla);
    }//GEN-LAST:event_jComboBox2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kayıt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kayıt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kayıt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kayıt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kayıt().setVisible(false);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPasswordField1;
    private java.awt.TextField textField1;
    private java.awt.TextField textField3;
    // End of variables declaration//GEN-END:variables
}
